version: '3.9'
services:
  postgres:
    image: postgres:16.1-alpine3.18
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=news_db
