export const GET_ARTICLES_REQUEST = 'GET_ARTICLES_REQUEST';
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS';
export const GET_ARTICLES_FAILURE = 'GET_ARTICLES_FAILURE';
export const GET_ARTICLES_RESET = 'GET_ARTICLES_RESET';

export const GET_ARTICLE_REQUEST = 'GET_ARTICLE_REQUEST';
export const GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS';
export const GET_ARTICLE_FAILURE = 'GET_ARTICLE_FAILURE';
export const GET_ARTICLE_RESET = 'GET_ARTICLE_RESET';

export const REVIEW_ARTICLE_REQUEST = 'REVIEW_ARTICLE_REQUEST';
export const REVIEW_ARTICLE_SUCCESS = 'REVIEW_ARTICLE_SUCCESS';
export const REVIEW_ARTICLE_FAILURE = 'REVIEW_ARTICLE_FAILURE';
export const REVIEW_ARTICLE_RESET = 'REVIEW_ARTICLE_RESET';

export const GET_ARTICLES_ADMIN_REQUEST = 'GET_ARTICLES_ADMIN_REQUEST';
export const GET_ARTICLES_ADMIN_SUCCESS = 'GET_ARTICLES_ADMIN_SUCCESS';
export const GET_ARTICLES_ADMIN_FAILURE = 'GET_ARTICLES_ADMIN_FAILURE';
export const GET_ARTICLES_ADMIN_RESET = 'GET_ARTICLES_ADMIN_RESET';

export const CREATE_ARTICLE_REQUEST = 'CREATE_ARTICLE_REQUEST';
export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS';
export const CREATE_ARTICLE_FAILURE = 'CREATE_ARTICLE_FAILURE';
export const CREATE_ARTICLE_RESET = 'CREATE_ARTICLE_RESET';
